// webapp/src/components/MetricCard.tsx
interface MetricCardProps {
  title: string
  value: string | number
  trend?: number
  color?: 'red' | 'green' | 'blue' | 'yellow'
}

export default function MetricCard({ title, value, trend, color = 'blue' }: MetricCardProps) {
  const colorClasses = {
    red: 'text-red-600 bg-red-100',
    green: 'text-green-600 bg-green-100',
    blue: 'text-blue-600 bg-blue-100',
    yellow: 'text-yellow-600 bg-yellow-100',
  }

  return (
    <div className="bg-white overflow-hidden shadow rounded-lg">
      <div className="p-5">
        <div className="flex items-center">
          <div className="flex-shrink-0">
            <div className={`rounded-md p-3 ${colorClasses[color]}`}>
              <svg className="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
              </svg>
            </div>
          </div>
          <div className="ml-5 w-0 flex-1">
            <dl>
              <dt className="text-sm font-medium text-gray-500 truncate">{title}</dt>
              <dd className="flex items-baseline">
                <div className="text-2xl font-semibold text-gray-900">{value}</div>
                {trend !== undefined && (
                  <div className={`ml-2 flex items-baseline text-sm font-semibold ${trend > 0 ? 'text-green-600' : 'text-red-600'}`}>
                    {trend > 0 ? '↑' : '↓'} {Math.abs(trend)}%
                  </div>
                )}
              </dd>
            </dl>
          </div>
        </div>
      </div>
    </div>
  )
}

// webapp/src/components/monitoring/MetricCard.vue
<template>
  <div class="bg-white overflow-hidden shadow rounded-lg">
    <div class="p-5">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <div :class="[
            'rounded-md p-3',
            color === 'blue' ? 'bg-blue-500' : '',
            color === 'green' ? 'bg-green-500' : '',
            color === 'red' ? 'bg-red-500' : '',
            color === 'yellow' ? 'bg-yellow-500' : '',
            color === 'purple' ? 'bg-purple-500' : '',
            color === 'orange' ? 'bg-orange-500' : ''
          ]">
            <component :is="icon" class="h-6 w-6 text-white" />
          </div>
        </div>
        <div class="ml-5 w-0 flex-1">
          <dl>
            <dt class="text-sm font-medium text-gray-500 truncate">
              {{ title }}
            </dt>
            <dd class="flex items-baseline">
              <div class="text-2xl font-semibold text-gray-900">
                {{ value }}
              </div>
              <div v-if="trend" class="ml-2 flex items-baseline text-sm font-semibold"
                :class="trend > 0 ? 'text-green-600' : 'text-red-600'">
                <component :is="trend > 0 ? 'TrendingUp' : 'TrendingDown'" class="h-4 w-4 flex-shrink-0" />
                <span class="ml-1">{{ Math.abs(trend) }}%</span>
              </div>
            </dd>
            <dd v-if="subtitle" class="text-sm text-gray-500">{{ subtitle }}</dd>
          </dl>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { TrendingUp, TrendingDown } from 'lucide-vue-next'

interface Props {
  title: string
  value: string | number
  subtitle?: string
  trend?: number
  icon: any
  color?: 'blue' | 'green' | 'red' | 'yellow' | 'purple' | 'orange'
}

const props = withDefaults(defineProps<Props>(), {
  color: 'blue'
})
</script>
